services:
  server:
    image: ivanilos/express-app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=30 # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
     
